# Generated by Django 4.0 on 2022-01-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('AP12', 'Apple AirPods 1&2'), ('AP3', 'Apple AirPod Pro'), ('AD12', 'Xiaomi AirDots 1&2'), ('AD3', 'Xiaomi AirDots 3')], max_length=4, null=True),
        ),
    ]
