# Generated by Django 4.0 on 2021-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller'), ('A', 'Animals'), ('F', 'Furry'), ('Fr', 'Fruits'), ('L', 'Leather'), ('C', 'Colors'), ('X', 'Xtra')], max_length=2),
        ),
    ]
